### ISSUE TITLE
Homebridge error Air Pressure range

### ISSUE THREAD

**Issue by kskenyon** [NorthernMan54/homebridge-tasmota#45]
Is there a way to eliminate or correct this Air Pressure Illegal Value error that fills up the logs?

2022-05-29T00:24:46.986Z Tasmota:mqtt emit homie/aurora-180701044/compressor/discharge-pressure 172.4
2022-05-29T00:24:46.987Z Tasmota:sensor statusUpdate WaterFurnace Compressor Discharge Pressure homie/aurora-180701044/compressor/discharge-pressure 172.4
[5/29/2022, 12:24:46 AM] [Tasmota] Updating 'WaterFurnace Compressor Discharge Pressure:Air Pressure' to 172.4
**_

> [5/29/2022, 12:24:46 AM] [homebridge-tasmota] This plugin generated a warning from the characteristic 'Air Pressure': characteristic was supplied illegal value: number 172 exceeded minimum of 300. See https://homebridge.io/w/JtMGR for more info.

_**
[5/29/2022, 12:24:46 AM] [homebridge-tasmota] Error: 
    at Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2142:105)
    at Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2045:14)
    at Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1457:20)
    at tasmotaSensorService.statusUpdate (/homebridge/node_modules/homebridge-tasmota/src/tasmotaSensorService.ts:247:29)
    at Mqtt.emit (node:events:526:28)
    at MqttClient.<anonymous> (/homebridge/node_modules/homebridge-tasmota/src/lib/Mqtt.ts:83:16)
    at MqttClient.emit (node:events:526:28)
    at MqttClient._handlePublish (/homebridge/node_modules/homebridge-tasmota/node_modules/mqtt/lib/client.js:1277:12)
    at MqttClient._handlePacket (/homebridge/node_modules/homebridge-tasmota/node_modules/mqtt/lib/client.js:410:12)
    at work (/homebridge/node_modules/homebridge-tasmota/node_modules/mqtt/lib/client.js:321:12)
2022-05-29T00:24:46.997Z Tasmota:mqtt emit homie/aurora-180701044/compressor/suction-pressure 171.4
2022-05-29T00:24:46.998Z Tasmota:sensor statusUpdate WaterFurnace Compressor Suction Pressure homie/aurora-180701044/compressor/suction-pressure 171.4
[5/29/2022, 12:24:46 AM] [Tasmota] Updating 'WaterFurnace Compressor Suction Pressure:Air Pressure' to 171.4

**Comment by NorthernMan54** [comment]
The maximum and minimum values for an air pressure sensor are here

https://github.com/NorthernMan54/homebridge-tasmota/blob/5859ddc2423c64ae4cc1db3e4aff39ae8da267b5/src/lib/CustomCharacteristics.ts#L68

And I based it on the the supported values from a BME280 sensor.   What range does your sensor support ?

**Comment by kskenyon** [comment]
Thanks, it’s actually mapped to suction pressure on a heat pump.  I’m not sure how low it can go.  It’s seems to usually be in the 100’s range.  It monitors the refrigerant charge.

I tried editing CustomCharacteristics.js in the application node_modules but that didn’t work and it wouldn’t be permanent on an update.  I’m running Homebridge in Docker.

Homekit is quite limited on what can be mapped to various sensors.

Thanks for getting back to me.

Kevin

**Comment by NorthernMan54** [comment]
I would need to do a release to permanently change the lower limit, just need a recommendation for a value

**Comment by kskenyon** [comment]
Since atmospheric pressure is never going to approach 300 hPa unless it’s in the eye of a tornado, I’d either drop it to 100 or 0 until Apple adds a Characteristic for pressures other than barometric pressure.

Thanks,

Kevin
