### ISSUE TITLE
Removing device from configuration causes restart

### ISSUE THREAD

**Issue by NorthernMan54** [NorthernMan54/homebridge-tasmota#52]
```
TypeError: Cannot read properties of undefined (reading 'removeAllListeners')
    at tasmotaPlatform.serviceCleanup (file:///var/lib/homebridge/node_modules/homebridge-tasmota/src/tasmotaPlatform.ts:484:48)
    at Mqtt.<anonymous> (file:///var/lib/homebridge/node_modules/homebridge-tasmota/src/tasmotaPlatform.ts:253:20)
    at Mqtt.emit (node:events:524:28)
    at Mqtt.handleHomeAssistantMessage (file:///var/lib/homebridge/node_modules/homebridge-tasmota/src/lib/Mqtt.ts:85:12)
    at Mqtt.handleMessage (file:///var/lib/homebridge/node_modules/homebridge-tasmota/src/lib/Mqtt.ts:58:14)
    at MqttClient.<anonymous> (file:///var/lib/homebridge/node_modules/homebridge-tasmota/src/lib/Mqtt.ts:49:12)
    at MqttClient.emit (node:events:524:28)
    at handlePublish (/var/lib/homebridge/node_modules/homebridge-tasmota/node_modules/mqtt/src/lib/handlers/publish.ts:172:11)
    at handle (/var/lib/homebridge/node_modules/homebridge-tasmota/node_modules/mqtt/src/lib/handlers/index.ts:31:17)
    at work (/var/lib/homebridge/node_modules/homebridge-tasmota/node_modules/mqtt/src/lib/client.ts:779:17)
[13/12/2024, 10:04:11] [Tasmota] Child bridge ended (code 1, signal null). The child bridge ended unexpectedly, which is normally due to the plugin not catching its errors properly. Please report this to the plugin developer by clicking on the 'Report An Issue' option in the plugin menu dropdown from the Homebridge UI. If there are related logs shown above, please include them in your report.
```

**Comment by NorthernMan54** [comment]
Fixed in https://github.com/NorthernMan54/homebridge-tasmota/releases/tag/0.2.1
